# Generated by Django 6.0.5 on 2026-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepaper',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notepaper',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
