# Generated by Django 6.0.5 on 2026-05-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notepaper_deleted_at_notepaper_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepaper',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
